# Generated by Django 3.1.7 on 2021-03-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=355)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Уборная',
                'verbose_name_plural': 'Уборные',
            },
        ),
        migrations.CreateModel(
            name='AddressImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_image', models.ImageField(upload_to='images')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet', to='api_side.entity')),
            ],
        ),
    ]
