# Generated by Django 3.1.7 on 2021-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0003_auto_20210316_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
