# Generated by Django 3.1.7 on 2021-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0008_auto_20210318_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=21, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=21, verbose_name='Долгота'),
        ),
    ]
