# Generated by Django 3.1.7 on 2021-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0009_auto_20210318_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.DecimalField(decimal_places=17, max_digits=18, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=18, verbose_name='Долгота'),
        ),
    ]
