# Generated by Django 3.1.7 on 2021-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0013_auto_20210318_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Долгота'),
        ),
    ]
