# Generated by Django 3.1.7 on 2021-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0014_auto_20210318_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
