# Generated by Django 3.1.7 on 2021-03-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_side', '0015_entity_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='is_publish',
            new_name='has_published',
        ),
    ]
